### ISSUE TITLE
Proposed resource: list of relevant conferences

### ISSUE THREAD

**Issue by benlk** [newsnerdery/newsnerdery#33]
Today in #watercooler, donohoe was askign for a list of relevant conferences and such.

Can this site have either a list of commonly-attended events, or a meta-list of event listings where such events commonly come up?

A list of commonly-attended events might include:
- NICAR
- SND

A list of lists might include:
- http://datadrivenjournalism.net/events
- https://source.opennews.org/articles/tags/events/

**Comment by danielbachhuber** [comment]
SRCCON https://srccon.org/
Media Party http://mediaparty.info/en/
